// Stub for @tauri-apps/api/window
// Used in development mode when not running in Tauri environment

export const getCurrentWindow = () => ({
  minimize: () => Promise.resolve(),
  maximize: () => Promise.resolve(),
  unmaximize: () => Promise.resolve(),
  toggleMaximize: () => Promise.resolve(),
  close: () => Promise.resolve(),
  isMaximized: () => Promise.resolve(false),
  isFocused: () => Promise.resolve(true),
  isResizable: () => Promise.resolve(true),
  isDecorated: () => Promise.resolve(true),
  isAlwaysOnTop: () => Promise.resolve(false),
  isFullscreen: () => Promise.resolve(false),
  isMinimized: () => Promise.resolve(false),
  isVisible: () => Promise.resolve(true),
  setTitle: () => Promise.resolve(),
  center: () => Promise.resolve(),
  requestUserAttention: () => Promise.resolve(),
  setResizable: () => Promise.resolve(),
  setDecorations: () => Promise.resolve(),
  setAlwaysOnTop: () => Promise.resolve(),
  setContentProtected: () => Promise.resolve(),
  setSize: () => Promise.resolve(),
  setMinSize: () => Promise.resolve(),
  setMaxSize: () => Promise.resolve(),
  setPosition: () => Promise.resolve(),
  setFullscreen: () => Promise.resolve(),
  setFocus: () => Promise.resolve(),
  setIcon: () => Promise.resolve(),
  setSkipTaskbar: () => Promise.resolve(),
  setCursorGrab: () => Promise.resolve(),
  setCursorVisible: () => Promise.resolve(),
  setCursorIcon: () => Promise.resolve(),
  setCursorPosition: () => Promise.resolve(),
  setIgnoreCursorEvents: () => Promise.resolve(),
  startDragging: () => Promise.resolve(),
  onResized: () => ({ unsubscribe: () => {} }),
  onMoved: () => ({ unsubscribe: () => {} }),
  onCloseRequested: () => ({ unsubscribe: () => {} }),
  onFocusChanged: () => ({ unsubscribe: () => {} }),
  onScaleChanged: () => ({ unsubscribe: () => {} }),
  onMenuClicked: () => ({ unsubscribe: () => {} }),
  onFileDropEvent: () => ({ unsubscribe: () => {} }),
  onThemeChanged: () => ({ unsubscribe: () => {} }),
});