/**
 * Predefined themes for LyricsAdapter
 */

import { ThemeConfig, THEME_IDS } from '../../types/theme';

export const predefinedThemes: ThemeConfig[] = [
  {
    id: THEME_IDS.DEFAULT,
    name: '经典蓝',
    description: '默认主题，经典蓝色调',
    icon: 'palette',
    isDark: true,
    tags: ['默认', '经典', '商务'],
    colors: {
      primary: '#2b8cee',
      primaryHover: '#4a9fef',
      primaryLight: 'rgba(43, 140, 238, 0.15)',
      backgroundDark: '#101922',
      backgroundGradientStart: '#101922',
      backgroundGradientEnd: '#1a2533',
      backgroundSidebar: '#16212e',
      backgroundCard: 'rgba(255, 255, 255, 0.05)',
      backgroundCardHover: 'rgba(255, 255, 255, 0.08)',
      textPrimary: '#ffffff',
      textSecondary: 'rgba(255, 255, 255, 0.7)',
      textMuted: 'rgba(255, 255, 255, 0.4)',
      borderLight: 'rgba(255, 255, 255, 0.1)',
      borderHover: 'rgba(255, 255, 255, 0.2)',
      accent: '#2b8cee',
      accentHover: '#4a9fef',
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#3b82f6',
      shadowColor: 'rgba(0, 0, 0, 0.3)',
      glowColor: 'rgba(43, 140, 238, 0.15)',
    },
    fonts: {
      main: "'Inter', system-ui, -apple-system, sans-serif",
      display: "'Inter', system-ui, -apple-system, sans-serif",
    },
    borderRadius: {
      sm: '4px',
      md: '8px',
      lg: '12px',
      xl: '16px',
      full: '9999px',
    },
  },
  {
    id: THEME_IDS.WARM,
    name: '暖米',
    description: '温暖米色，简约雅致',
    icon: 'light_mode',
    isDark: false,
    tags: ['极简', '暖色', '简约'],
    colors: {
      primary: '#b8956a',
      primaryHover: '#a68458',
      primaryLight: 'rgba(184, 149, 106, 0.2)',
      backgroundDark: '#f5f0e8',
      backgroundGradientStart: '#f5f0e8',
      backgroundGradientEnd: '#ebe5d9',
      backgroundSidebar: '#e8e2d6',
      backgroundCard: 'rgba(255, 255, 255, 0.6)',
      backgroundCardHover: 'rgba(255, 255, 255, 0.85)',
      textPrimary: '#3d3028',
      textSecondary: '#5a4a3a',
      textMuted: '#8a7a6a',
      borderLight: 'rgba(61, 48, 40, 0.12)',
      borderHover: 'rgba(61, 48, 40, 0.25)',
      accent: '#b8956a',
      accentHover: '#a68458',
      success: '#5a9e5f',
      warning: '#c49a4a',
      error: '#c46a6a',
      info: '#6a8ec4',
      shadowColor: 'rgba(61, 48, 40, 0.1)',
      glowColor: 'rgba(184, 149, 106, 0.2)',
    },
    fonts: {
      main: "'Inter', system-ui, -apple-system, sans-serif",
      display: "'Inter', system-ui, -apple-system, sans-serif",
    },
    borderRadius: {
      sm: '4px',
      md: '8px',
      lg: '12px',
      xl: '16px',
      full: '9999px',
    },
  },
  {
    id: THEME_IDS.BRUTALIST,
    name: '粗粝黄',
    description: '高对比硬边框，海报感粗粝风格',
    icon: 'category',
    isDark: false,
    tags: ['粗粝', '高对比', '黄色'],
    colors: {
      primary: '#f5e642',
      primaryHover: '#fff04a',
      primaryLight: 'rgba(245, 230, 66, 0.35)',
      backgroundDark: '#f5f5f0',
      backgroundGradientStart: '#f5f5f0',
      backgroundGradientEnd: '#e8e5d8',
      backgroundSidebar: '#f5e642',
      backgroundCard: '#fffdf0',
      backgroundCardHover: '#f5e642',
      textPrimary: '#0a0a0a',
      textSecondary: '#2f2f2a',
      textMuted: '#7b776b',
      borderLight: '#0a0a0a',
      borderHover: '#0a0a0a',
      accent: '#e8180a',
      accentHover: '#b81208',
      success: '#00b84f',
      warning: '#f59e0b',
      error: '#e8180a',
      info: '#1769ff',
      shadowColor: 'rgba(10, 10, 10, 0.35)',
      glowColor: 'rgba(245, 230, 66, 0.45)',
    },
    fonts: {
      main: "'Arial Black', 'Impact', system-ui, -apple-system, sans-serif",
      display: "'Arial Black', 'Impact', system-ui, -apple-system, sans-serif",
      mono: "'SFMono-Regular', Consolas, monospace",
    },
    borderRadius: {
      sm: '0px',
      md: '0px',
      lg: '2px',
      xl: '4px',
      full: '0px',
    },
    controls: {
      panelBackground: '#f5f5f0',
      panelBackgroundGlass: 'rgba(245, 245, 240, 0.92)',
      panelBackgroundGlassStrong: 'rgba(245, 245, 240, 0.96)',
      panelFloatingBackground: '#f5f5f0',
      panelBorder: '#0a0a0a',
      panelShadow: '8px 8px 0 #0a0a0a',
      containerBackground: '#fffdf0',
      containerBorder: '#0a0a0a',
      itemBackgroundHover: '#f5e642',
      itemBackgroundActive: '#0a0a0a',
      itemForegroundActive: '#f5e642',
      itemShadowActive: '4px 4px 0 #0a0a0a',
      iconBackground: '#fffdf0',
      iconBackgroundActive: '#0a0a0a',
      iconForeground: '#0a0a0a',
      iconForegroundHover: '#e8180a',
      iconForegroundActive: '#f5e642',
      actionBackground: '#fffdf0',
      actionBackgroundHover: '#f5e642',
      actionBackgroundActive: '#0a0a0a',
      actionForeground: '#0a0a0a',
      actionForegroundHover: '#0a0a0a',
      actionForegroundActive: '#f5e642',
      actionShadow: '3px 3px 0 #0a0a0a',
      actionShadowActive: '4px 4px 0 #e8180a',
      primaryButtonBackground: '#0a0a0a',
      primaryButtonForeground: '#f5e642',
      primaryButtonShadow: '5px 5px 0 #e8180a',
      sliderTrack: '#d7d3c4',
      sliderFill: '#e8180a',
      sliderSecondaryFill: '#0a0a0a',
      inputBackground: '#fffdf0',
      inputBorder: '#0a0a0a',
      inputBorderActive: '#e8180a',
    },
    appearance: {
      surfaceRadius: '0px',
      controlRadius: '0px',
      buttonRadius: '0px',
      mediaRadius: '0px',
      progressRadius: '0px',
      progressHeight: '6px',
      surfaceBorderWidth: '3px',
      controlBorderWidth: '3px',
      panelBorderWidth: '4px',
      surfaceShadow: '6px 6px 0 #0a0a0a',
      surfaceShadowHover: '8px 8px 0 #0a0a0a',
      textBodyWeight: '700',
      textHeadingWeight: '900',
      textButtonWeight: '900',
      headingLetterSpacing: '0',
      buttonLetterSpacing: '0.12em',
      controlTextTransform: 'uppercase',
    },
  },
];

// Helper function to get the default theme
export function getDefaultTheme(): ThemeConfig {
  return predefinedThemes.find(theme => theme.id === THEME_IDS.DEFAULT)!;
}
