/**
 * Predefined themes for LyricsAdapter
 */

import { ThemeConfig, THEME_IDS } from '../../types/theme';

export const predefinedThemes: ThemeConfig[] = [
  {
    id: THEME_IDS.DEFAULT,
    name: '默认',
    description: '与启动图标背景一致的粉蓝配色',
    icon: 'palette',
    isDark: false,
    tags: ['默认', '粉蓝'],
    colors: {
      primary: '#b6408d',
      primaryHover: '#a83d88',
      primaryLight: 'rgba(238, 166, 217, 0.24)',
      backgroundDark: '#f5e2f6',
      backgroundGradientStart: '#ffc5d1',
      backgroundGradientEnd: '#7cc6fc',
      backgroundSidebar: '#f7eef9',
      backgroundCard: 'rgba(255, 255, 255, 0.72)',
      backgroundCardHover: 'rgba(255, 255, 255, 0.94)',
      textPrimary: '#31283a',
      textSecondary: '#5d536a',
      textMuted: '#796e84',
      borderLight: 'rgba(83, 67, 102, 0.12)',
      borderHover: 'rgba(83, 67, 102, 0.24)',
      accent: '#4e6ec8',
      accentHover: '#405fba',
      success: '#3f8f70',
      warning: '#b47722',
      error: '#bd4f68',
      info: '#4e6ec8',
      shadowColor: 'rgba(71, 55, 91, 0.12)',
      glowColor: 'rgba(182, 64, 141, 0.22)',
    },
    fonts: {
      main: "'Inter', system-ui, -apple-system, sans-serif",
      display: "'Inter', system-ui, -apple-system, sans-serif",
    },
    borderRadius: {
      sm: '4px',
      md: '8px',
      lg: '12px',
      xl: '16px',
      full: '9999px',
    },
  },
  {
    id: THEME_IDS.BRUTALIST,
    name: '粗粝黄',
    description: '高对比硬边框，海报感粗粝风格',
    icon: 'category',
    isDark: false,
    tags: ['粗粝', '高对比', '黄色'],
    colors: {
      primary: '#f5e642',
      primaryHover: '#fff04a',
      primaryLight: 'rgba(245, 230, 66, 0.35)',
      backgroundDark: '#f5f5f0',
      backgroundGradientStart: '#f5f5f0',
      backgroundGradientEnd: '#e8e5d8',
      backgroundSidebar: '#f5e642',
      backgroundCard: '#fffdf0',
      backgroundCardHover: '#f5e642',
      textPrimary: '#0a0a0a',
      textSecondary: '#2f2f2a',
      textMuted: '#7b776b',
      borderLight: '#0a0a0a',
      borderHover: '#0a0a0a',
      accent: '#e8180a',
      accentHover: '#b81208',
      success: '#00b84f',
      warning: '#f59e0b',
      error: '#e8180a',
      info: '#1769ff',
      shadowColor: 'rgba(10, 10, 10, 0.35)',
      glowColor: 'rgba(245, 230, 66, 0.45)',
    },
    fonts: {
      main: "'Arial Black', 'Impact', system-ui, -apple-system, sans-serif",
      display: "'Arial Black', 'Impact', system-ui, -apple-system, sans-serif",
      mono: "'SFMono-Regular', Consolas, monospace",
    },
    borderRadius: {
      sm: '0px',
      md: '0px',
      lg: '2px',
      xl: '4px',
      full: '0px',
    },
    controls: {
      panelBackground: '#f5f5f0',
      panelBackgroundGlass: 'rgba(245, 245, 240, 0.92)',
      panelBackgroundGlassStrong: 'rgba(245, 245, 240, 0.96)',
      panelFloatingBackground: '#f5f5f0',
      panelBorder: '#0a0a0a',
      panelShadow: '8px 8px 0 #0a0a0a',
      containerBackground: '#fffdf0',
      containerBorder: '#0a0a0a',
      itemBackgroundHover: '#f5e642',
      itemBackgroundActive: '#0a0a0a',
      itemForegroundActive: '#f5e642',
      currentTrackForeground: '#0a0a0a',
      currentTrackBandTint: 'transparent',
      itemShadowActive: '4px 4px 0 #0a0a0a',
      iconBackground: '#fffdf0',
      iconBackgroundActive: '#0a0a0a',
      iconForeground: '#0a0a0a',
      iconForegroundHover: '#e8180a',
      iconForegroundActive: '#f5e642',
      actionBackground: '#fffdf0',
      actionBackgroundHover: '#f5e642',
      actionBackgroundActive: '#0a0a0a',
      actionForeground: '#0a0a0a',
      actionForegroundHover: '#0a0a0a',
      actionForegroundActive: '#f5e642',
      actionShadow: '3px 3px 0 #0a0a0a',
      actionShadowActive: '4px 4px 0 #e8180a',
      primaryButtonBackground: '#0a0a0a',
      primaryButtonForeground: '#f5e642',
      primaryButtonShadow: '5px 5px 0 #e8180a',
      sliderTrack: '#d7d3c4',
      sliderFill: '#e8180a',
      sliderSecondaryFill: '#0a0a0a',
      inputBackground: '#fffdf0',
      inputBorder: '#0a0a0a',
      inputBorderActive: '#e8180a',
    },
    appearance: {
      controlbarRadius: '0px',
      surfaceRadius: '0px',
      controlRadius: '0px',
      buttonRadius: '0px',
      mediaRadius: '0px',
      progressRadius: '0px',
      progressHeight: '6px',
      surfaceBorderWidth: '3px',
      controlBorderWidth: '3px',
      panelBorderWidth: '4px',
      surfaceShadow: '6px 6px 0 #0a0a0a',
      surfaceShadowHover: '8px 8px 0 #0a0a0a',
      elevatedShadow: '6px 6px 0 #0a0a0a',
      textBodyWeight: '700',
      textHeadingWeight: '900',
      textButtonWeight: '900',
      headingLetterSpacing: '0',
      buttonLetterSpacing: '0.12em',
      controlTextTransform: 'uppercase',
      listItemBorder: '#0a0a0a',
      listItemGap: '0px',
      listItemPaddingY: '16px',
      // 粗粝风每行已有 3px 粗黑边框，浮动跟随滑块在此主题下会退化为孤立的
      // 硬阴影方块（tint 为 transparent）且易错位；改用行内实色高亮，无跟随动画。
      playingIndicator: 'inline',
    },
  },
];

// Helper function to get the default theme
export function getDefaultTheme(): ThemeConfig {
  return predefinedThemes.find(theme => theme.id === THEME_IDS.DEFAULT)!;
}
